### PR TITLE
add background of login page

### PR DESCRIPTION
**Pull request by baquer**
Hey @cpg please provide me all the specification needed in this app

### CODE REVIEW

**Comment by cpg** [comment]
I have some feedback on the details.

It should be "Username *or* email" an "Password" (not "password").

After that, this will partially taking care of the UI part in #4.

**Comment by baquer** [comment]
Okay I will correct and work on this

**Comment by csoni111** [comment]
Also it would be better if instead of adding a full image in the background, we make the background color as blue (or black as in android app) and only add the logo image on the top with constraints such that it remains on the top of text fields.

**Comment by snuff4** [comment]
@csoni111 I like that too! I'm working on that, and putting the logo image in the centre of the launch screen.

**Comment by baquer** [comment]
Yeah I am working on it

**Comment by baquer** [comment]
Conflicting files
AmahiAnywhere/AmahiAnywhere/Assets.xcassets/AppIcon.appiconset/Contents.json
AmahiAnywhere/AmahiAnywhere/Assets.xcassets/LaunchImage.launchimage/Contents.json

These files are having no conflicts ,i checked it twice

**Comment by cpg** [comment]
Thanks for the effort! Let's attempt to coordinate a little more in the future so we avoid parallel/competitive work as well as frustration.

**Comment by baquer** [comment]
Yeah your welcome 😊 Sir

**Pull request closed without merging**
