### PR TITLE
Global layout and SDWebImage Update and Fix

### PR DESCRIPTION
**Pull request by Marton-Zeisler**
- I updated the SDWebImage pod to 5.0.6
- I also Implemented a global layout view mode. So now if you change the layout from grid to list mode and go inside a folder then the layout will be the same.

### CODE REVIEW

**Comment by cpg** [comment]
There appears to be no sound coming out of the speakers when playing music files.

Other apps play fine. If I switch to `beta` the audio plays fine as well.

**Comment by Marton-Zeisler** [comment]
I tested it on both simulator and my physical device and there is sound for me. I didn't change any code regarding the music player. Can you try again? 

@iswiftshek If you have time, could you download this PR and try to play a song and see if there is sound?

**Comment by iswiftshek** [comment]
I just tested it, works well on my end. @Marton-Zeisler @cpg

**Comment by Marton-Zeisler** [comment]
Thanks.

@cpg I added another feature so the layout stays the same even after you close the app. I am using UserDefaults to keep track which layout view mode the user selected.

Also, regarding the sound issue, if you ran the app on your phone, can you try running it on a simulator? Or if you ran it on simulator, try running it on a physical device, it should work.

**Comment by cpg** [comment]
After a clean merge into my own branch and clean/rebuild, it plays audio fine.

About the layout "staying the same" ... I am not sure I undestand. I did this, in my Music share, I have a folder called Jazz. I changed to layout by date and it did not have it after I closed and reopened the app. Was that supposed to be remembered?

**Comment by Marton-Zeisler** [comment]
That's the sorting selection, not the layout. The layout is for switching between grid and list view but I can also save the sorting selection so that stays the same even after closing the app

**Comment by Marton-Zeisler** [comment]
@cpg The app now saves the sorting selection but only for the online files because the downloads section doesn't have the "Sort By Type" sorting option so once we add the offline folders support then that will be fixed too.

**Comment by cpg** [comment]
OK, I thought the layout included the grouping (and therefore the sorting).

**Comment by cpg** [comment]
I think the layout and sorting order should be saved for each view (each share, each folder). Problem is what to do with stale state and how to clear it over time. Maybe it's not huge so it's ok to keep it around unused. Small bloat.

**Pull request merged**
