### PR TITLE
Tab Bar + Fixes for Settings

### PR DESCRIPTION
**Pull request by Marton-Zeisler**
Added a Tab Bar based navigation system for the app.

Fixes and improvements for the **Settings** screen:
- Design and color improvements
- Added a selection colour to each field to indicate which settings item was pressed by the user
- Removed unnecessary pop up when no email account is setup and user tries to send feedback. iOS already displays a pop up warning
- Fixed the order of the sign out action buttons. Usually apps put the delete button on the left side and the delete(main action) on the right side

Simulator Screen Shot - iPhone 8 - 2019-05-28 at 12 18 10

### CODE REVIEW

**Comment by cpg** [comment]
I think this voids the need for having a separate entry for "OFFLINE" with just the downloads, since it's available in the tab bar

**Comment by Marton-Zeisler** [comment]
This PR is just for the tab bar and the settings screen, the next PR will include the completely redesigned HDA screen and that one won't have the downloads button

**Comment by cpg** [comment]
And presumably the top-right icon for downloads in each share/folder page, I assume? :-)

**Comment by Marton-Zeisler** [comment]
Yes, the new design of those screens won't include that.

**Pull request merged**
