### PR TITLE
Requesting App Ratings

### PR DESCRIPTION
**Pull request by anubhavsingh16**
In this Pull request, I'm making a popup for Requesting App Ratings from users. Because rating help is to improve your ranking on the App Store.

issue #271 

Amahi rating

The Submit button will appear greyed out since we are in development mode. It will appear enabled for users using your app through the App Store.

amahi rating 2

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
#272 solved in this Pull Request.

**Comment by anubhavsingh16** [comment]
When and where to insert rating requests.

**Where -** I think after logout is the best place to ask for a rating, **When-** after user login and logout **four** times he/she experience full app then we ask for rating is best time.

And we can't display an in-app prompt that asks for a rating until the user experiences it 4 times and the user is not asked to review the same version of your app multiple times which is apple requirement.

**Comment by anubhavsingh16** [comment]
@cpg Please have a look this PR.

**Comment by cpg** [comment]
closing this one to work on #280 or a new one.

**Pull request closed without merging**
