### PR TITLE
hex: color error and lightbox error

### PR DESCRIPTION
**Pull request by anubhavsingh16**
This Pull Request solved to issues:
1- incorrect argument label in call `have 'hex:`
2- lightbox Not working in iOS 13. App getting Freeze. #278 

- for named color, I create new color sets to implement `UIColor(named: "named color")` property and fix this bug.

- On iOS 13, the default UIModalPresentationStyle changed from .fullScreen to .automatic.
To fix the issue where the controller isn't dismissed properly, change the modalPresentationStyle on LightboxController back to UIModalPresentationStyle.fullScreen

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@cpg Please have a look.

**Comment by cpg** [comment]
I had to update the podfile to get SDWebImage 5.8.3 (was 5.8.1).

With this, we lose the changes that made it usable in iOS 12. So in iOS 12 it's not visible due to background colors, etc.

Can this is fixed?

**Comment by cpg** [comment]
How positive are you that `named` parameters allow "hex style" of color in the string? (with or without the `0x`)

I think I recently brushed at the docs for that topic and named was for colors that had a "name" like "red" or whatever. But I could be wrong.

**Comment by anubhavsingh16** [comment]
> How positive are you that `named` parameters allow "hex style" of color in the string? (with or without the `0x`)
> 
> I think I recently brushed at the docs for that topic and named was for colors that had a "name" like "red" or whatever. But I could be wrong.

You are right I have to make new color sets for same name to use as named colurs. And I just fix this in my new commit.

**Comment by anubhavsingh16** [comment]
I test this commit with iOS 13, ios 12, ios 11 simulators.

**Pull request merged**
