### PR TITLE
Feature: Implement Thumbnail Generators for Videos, Audio files and Documents.

### PR DESCRIPTION
**Pull request by codedentwickler**
A Preview of the changes is shown below.

RPReplay_Final1554055245

Also the Thumbnails generated are cached for Reuse.

### CODE REVIEW

**Comment by iswiftshek** [comment]
This looks great, nicely done! @codedentwickler

**Comment by codedentwickler** [comment]
Thanks man. Please help test on your end too. So we are sure everything works well

**Comment by iswiftshek** [comment]
Yes tested it. Works well on my end 👍

**Comment by cpg** [comment]
So this means that ALL files are fully downloaded just browsing? .. or?

**Comment by codedentwickler** [comment]
Just browsing. 

For videos, it jumps to a time in the video and takes a snapshot.

For audio files, it extracts the audio metadata which contains the thumbnail art and some other information. 

For Documents, it takes the snapshot of the first page.

All these are done without downloading the entire file.

**Comment by iswiftshek** [comment]
I was just testing the app, and it crashed with this (probably becuase of poor internet connectivity):

Screenshot 2019-04-01 at 5 21 48 PM

So, just to be safe I think we should put the code like this:

`guard durationSeconds.isFinite else {
    // return 
}`

And maybe put this in a block and then set the time and image. Or some other way, you know, to handle the potential error.  @codedentwickler

**Comment by codedentwickler** [comment]
Thanks for pointing that out @iswiftshek. I will investigate the issue and fix it.

**Comment by codedentwickler** [comment]
I made changes to fix that issue. Please help review again @cpg @iswiftshek

**Pull request merged**
