### PR TITLE
Login page in support of Diferent Mode

### PR DESCRIPTION
**Pull request by vaibhavbisht06**
The login page will support different mode (Any, Light, Dark)
## Dark Mode:
Screenshot 2020-02-03 at 11 10 26 AM
## Light Mode:
Screenshot 2020-02-03 at 11 10 12 AM
## Any Mode:
Screenshot 2020-02-03 at 11 10 26 AM
### Issue Cleared
This Pull request is used to close the issue #264

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@vaibhavbisht06 for the Login page of Different mode I already send Pull Request #265 12 days ago.

**Comment by vaibhavbisht06** [comment]
**@anubhavsingh16** Actually when I saw this issue there was no PR. Then I was not able to keep track of the PR and this PR was in Pipe Line. 
PS(edit the spelling of Launch from **Support dark as well as a light mode in the login page as well as in Lunch screen** ) in your PR  #265

**Comment by anubhavsingh16** [comment]
> **@anubhavsingh16** Actually when I saw this issue there was no PR. Then I was not able to keep track of the PR and this PR was in Pipe Line.
> PS(edit the spelling of Launch from **Support dark as well as a light mode in the login page as well as in Lunch screen** ) in your PR #265

thanks

**Comment by anubhavsingh16** [comment]
> **@anubhavsingh16** Actually when I saw this issue there was no PR. Then I was not able to keep track of the PR and this PR was in Pipe Line.
> PS(edit the spelling of Launch from **Support dark as well as a light mode in the login page as well as in Lunch screen** ) in your PR #265

and I send PR at the same time when I make this issue and thanks for the typo error.

**Pull request closed without merging**
