### PR TITLE
Pause video player when the currently used audio device is disconnected

### PR DESCRIPTION
**Pull request by codedentwickler**
Ensure the video player pause when headphones or bluetooth devices are disconnected. implement #70

### CODE REVIEW

**Comment by cpg** [comment]
This has an interesting behavior that may be more than what's needed, which differs from the built-in video media player (which I can access with the latest Amahi app in the app store).

When powering off the bluetooth device (BTD) or removing the headphones, independently, it works as expected.

When listening with the headphones and the BTD is on, then powered off, it works as expected (the headphones still work).

Curiously, when listening with the headphones and the BTD is connected (but not used) and the headphones are unplugged, the audio switches to the BTD automatically.

I think the check `if !AVAudioSession.isHeadphonesConnected {}` is not necessary, so losing the current audio route is necessary. Hence the whole `AVAudioSessions` extension is not necessary, I believe. Removing the check appears to have the required behavior, unless I'm mistaken.

**Comment by codedentwickler** [comment]
Yes, removing the check will just pause the video and not switch to the next available device.

**Comment by codedentwickler** [comment]
I have updated made that change I also tested to make sure everything works fine.

**Comment by cpg** [comment]
1) is `AVAudioSession.swift` needed at all? remove it please
2) there are some print statements
3) removing the if check means the code should be reindented, not just removing those two lines.

**Comment by cpg** [comment]
closes #70

**Pull request merged**
