### PR TITLE
Audio Player Gestures

### LINKED ISSUE #205: Music Player gestures
The following feature is needed:

- User can swipe left/right on the thumbnail image to move to the next/previous track, it would be like Spotify so if you release the swipe gesture too early then nothing will happen

To do that, the audio player should have a list of all the music files from the selected folder so it can load the thumbnails. These thumbnails are already loaded when the user opened the selected folder so it doesn't need to be re-downloaded.

### LINKED ISSUE #313: When the music player opens and the song is played, it restarts the first song after exactly 10 seconds
I am not 100% sure what are the conditions of this, however, when the music player opens and the song is played, it restarts the first song after exactly 10 seconds.

This happens at least when opening a song from the base, now when going to a song next, etc.

### LINKED ISSUE #325: Audio Player UI freezes for a few seconds on start
**Describe the bug**
A list of `AVPlayerItem` passed to `AudioPlayerDataModel.swift` is processed in a for loop to extract the meta data. This takes considerable amount of time and the app freezes for this duration.
**To Reproduce**
1. Navigate to the share containing list of songs.
2. Tap on a song from a list.

**Expected behavior**
- Player should load a few songs in the background thread while showing a loader in the UI. Also, instead of processing the complete list in one go, we should process on demand.

**Desktop :**
 - Version of the app : 3.3
 - Build : 330

**Device :**
 - OS:  iOS 13.6
 - [ iPhoneSE-2nd gen]

### PR DESCRIPTION
**Pull request by ShresthPratapSingh**
### Description
This PR adds swipe gestures to navigate between songs.
This PR also implements progressively fetching of Metadata for better experience.

Fixes #205 
Fixes #313 
Fixes #325    

### Type of Change:

- Code
- Quality Assurance
- User Interface

### How Has This Been Tested?
Tested on iOS simulators(iOS 11, 12, 13) and on device (iOS 13.6)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by cpg** [comment]
Great improvement. This is what I came across:

- [x] When repeat-one-song is in effect, I notice that the list of songs remains, but pressing on any son yields the currently playing song. UX wise, tapping on one song then hearing another is not good. OTOH, repeating the one song is _logical_. Perhaps tapping on one of the songs on what's next ought to play that and make that the repeat-one-song track! Easy?
- [x] When repeat-one-song is in effect, the image swiping effect does not finish. It leaves the artwork half way slid on the screen. Easy to fix?
- [x] The artwork aspect ratio is not preserved still.

**Comment by ShresthPratapSingh** [comment]
@cpg please let me know the device you're using for testing so that I replicate the image aspect ratio issue on that.

**Comment by cpg** [comment]
It's a year old iphone x. i shared the song with you. please fix the conflicts, validate all is working.

**Comment by ShresthPratapSingh** [comment]
@cpg I've implemented the suggested changes and resolved conflicts. This PR is ready to merge.

**Pull request merged**
