### PR TITLE
Fix video player: fading of UI elements should start after play starts

### LINKED ISSUE #60: video player: fading of UI elements should start after play starts
currently, fading of UI elements starts shortly after the player takes the screen. often, play takes a few seconds to start (possibly buffering?), but the UI has faded, so it can be a little worrying to see a black screen.

the fading should start after play starts, ideally one second in or so after play actually starts.

### PR DESCRIPTION
**Pull request by codedentwickler**
Ensure Video controls does not fade while the video is buffering. This PR fixes #60

### CODE REVIEW

**Comment by cpg** [comment]
It's one small change but 14 commits with lots of noise, possibly 13 too many commits.

Would it be possible to adopt a more streamlined process?

**Comment by codedentwickler** [comment]
@cpg. I pushed just one commit. You can confirm in the logs above. It seems GIT is seeing my previous commits that have been merged as new commits. I don't know what is causing this.

**Comment by snuff4** [comment]
@codedentwickler [Squashing commits](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git) might help?

**Comment by codedentwickler** [comment]
Branch has diverged as some point earlier. The changes in this PR has been resubmitted in #65. Closing..

**Pull request closed without merging**
