### PR TITLE
New redesigned files and folders screen

### PR DESCRIPTION
**Pull request by Marton-Zeisler**
Completely redesigned and improved the files/folders screen.
New features:
- New search bar, it's now in the navigation bar and only appears when the user wants to perform a search
- New sort selector, there's now a single button to select the sorting method. Tapping it brings up the  list of available sorting methods. The view comes up from the bottom with a nice slide up animation
- New 2 sorting methods: Sort by Size and Sort by Type. Sort by Type will sort the files/folders by its type, folders will come first and then files
- New 2 layouts for files and folders. It features a grid layout view and a list view. User can switch between the two views by tapping on the layout view selector in the top right corner
- Sections added to the layout to help organise the list of files. Section names depend on the selected sorting method. For example, if the selected sorting method is "Sort by Type", then the section names will be "Folders" and "Files". If the selected sorting method is "Sort by Modified", then the section names will take the months of the sections of the files
- New file and folder cells with better layout and larger icons and new swipe actions in the list view to share and download files
- Footer view added to display the number of files and folders
- Global sorting method selection. The sorting method will stay the same throughout the stack of files view controllers. For example, if user selects a "Sort by Modified" sorting method and opens a folder then the new files view controller will keep the selected sorting method

Simulator Screen Shot - iPhone 8 - 2019-06-18 at 20 07 31
Simulator Screen Shot - iPhone 8 - 2019-06-18 at 20 07 39
Simulator Screen Shot - iPhone 8 - 2019-06-18 at 20 07 53
Simulator Screen Shot - iPhone 8 - 2019-06-18 at 20 07 58
Simulator Screen Shot - iPhone 8 - 2019-06-18 at 20 08 40

### CODE REVIEW

**Comment by cpg** [comment]
Getting this build error now:

`Frameworks/Alamofire.framework: errSecInternalComponent`

**Comment by Marton-Zeisler** [comment]
That error is related to code signing issue. Can you try to do a clean build and also try to run it on a simulator? Also make sure you're signed in with your apple developer account in Xcode.

**Comment by cpg** [comment]
I had in fact done all of the things you mention prior to reporting the error.

I did not think of running it in a sim because I though this looked like a compile-time error. However, I tried it and it runs in a sim, somehow.

That said, it appears that this rearrangement breaks the music player some. I think I got the breakage down as follows.

It appears that the alphabetical classification breaks the list of songs in a folder in "groups." So ... for example, if I have 200 songs, but only one that starts with, say, `B` ... when I play it, it starts, but if I click on the forward icon, it plays again itself (and the repeat icon gets selected).

When there are three songs starting with one letter, there is a group of them, and I can play from one to the next, and the next and so on, always within the group. Selecting random only plays them in the group randomly.

If I sort by modified time, then there is one group and I can play them all in order or random.

**Comment by iswiftshek** [comment]
I looked into what's happening behind the scenes. So whenever groups are made, each group acts like a different playlist i.e. every group starts with an **index 0**.

So whenever we select a song in a group, only the urls of the files in that group are being passed (thereby making the groups act like different playlists). 
[Maybe we can tweak the way files are divided into groups? @Marton-Zeisler]

When you play songs in a particular group, they play until the last song in the group is reached. And when that happens, and you press "Next", the songs of that playlist (of that group) start to repeat.

The repeat icon gets enabled when you've completed a playlist and press next (which means that the you want to play the songs again, so that's why I set it to enable "Play all" in that case). If there is only one song in a group, and you hit next, using the same logic it repeats the playlist of "1 song" and the repeat icon gets selected.

When the files are in order (grouped as a whole), the indexes are 0, 1, 2, 3.. and thus, all the files are passed and the music player acts fine.

**Comment by Marton-Zeisler** [comment]
@cpg, @iswiftshek, Thank you for pointing out this bug. I fixed it now.

The app now keeps track of the indexPaths of each image and audio file so the FilesViewController passes every filtered image or audio file to the media player.

My approach is also more efficient than the previous version as it only iterates through the indexPaths of images or audio files instead of iterating over the entire files array.

**Pull request merged**
