### PR TITLE
Search bar selection and rotation fixes

### LINKED ISSUE #332: Search textfield is not working
## Description:
The search text field of the navbar is not taking input. Inside shares when we try to tap on the search text field then Sort options pop-up.

## Screen Recording:
video-to-gif-converter

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
This Pull Request solve the issue of search bar navigation, Unresponsive search box and Duplication or triplication of the search icon at the top right.

Fixes #332 

### Type of Change:

- Code
- Quality Assurance

### How Has This Been Tested?
search-bar

### CODE REVIEW

**Comment by cpg** [comment]
My suggestions are:

- Autofocus of the search box -- so that the user does not have to tap twice
- The second issue is some space below the search box and the rest of the image, _when the search box is not cursor-focused_

**Comment by anubhavpulkit** [comment]
> My suggestions are:
> 
> * Autofocus of the search box -- so that the user does not have to tap twice
> * The second issue is some space below the search box and the rest of the image, _when the search box is not cursor-focused_

@cpg I think again about autofocus and find that in our scenario we use the search button to just open the search bar. So we have to tap again on the search bar to type(input) on the search bar. I think we don't have any case to autofocus search bar by just tapping on the search button.

**Comment by cpg** [comment]
I cannot parse that English well. It sounds like that language implies there are no other apps showing autofocus, therefore we should not do it?

The google calendar app has a search icon that brings up the search bar with the cursor set and the focus on, bringing up the keyboard immediately.

In any case, right now just displaying an intermediate box (with no text at all inside or a cancel text; like what it does once we tap it) with wrong margins seems weird in terms of UX.

**Comment by cpg** [comment]
Also, if one pulls down on the main screen of the iPhone, a search box already focused and with the keyboard comes up.

**Comment by anubhavpulkit** [comment]
> Also, if one pulls down on the main screen of the iPhone, a search box already focused and with the keyboard comes up.

We can do this through a design pattern concept called the first responder. And I'm working on this most probably I will update this PR tonight with autofocus functionality(search box already focused and with the keyboard comes up).

**Comment by cpg** [comment]
No progress.

**Pull request closed without merging**
