### PR TITLE
Google cast added in video-player

### LINKED ISSUE #314: Google Cast support
Add new feature Google Cast SDK to extend the iOS app to direct its streaming video to a TV.  The app becomes the remote control to play, pause, seek, rewind, stop and otherwise control the media.

### PR DESCRIPTION
**Pull request by anubhavpulkit**
### Description
Google Cast allows users to cast content from a mobile device to a TV. Users can then use their mobile device as a remote control for media playback on the TV. In this PR we add an expanded controller. I'm using google cast official tutorial to add this feature.

Fixes #314

### Type of Change:

- Code
- Quality Assurance
- User Interface

### How Has This Been Tested?
I can't test this feature because I don't have Chromecast devices to test this feature.

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by cpg** [comment]
This does not appear to do anything for me.

However, I have tried

- Youtube on my same iOS device, which instantly recognized my cast device (a TV) and played high-res content on it
- I watched the debugger logs in xcode and the app's google cast sdk does see my cast device, judging by these logs
`com.google.cast.CastDevice, ID = ..., instance = (null), name = 'Living Room TV', address = 192.168.32.33:8009> rawID = ...`

**Comment by anubhavsingh16** [comment]
> This does not appear to do anything for me.
> 
> However, I have tried
> 
> * Youtube on my same iOS device, which instantly recognized my cast device (a TV) and played high-res content on it
> * I watched the debugger logs in xcode and the app's google cast sdk does see my cast device, judging by these logs
>   `com.google.cast.CastDevice, ID = ..., instance = (null), name = 'Living Room TV', address = 192.168.32.33:8009> rawID = ...`

ok

**Comment by anubhavpulkit** [comment]
@cpg I have a question related to testing when you play the video in Amhai-iOS app while test( when Chrome cast network is present)
cast
 Does cast symbol appear at the top of video player?

**Comment by cpg** [comment]
No. That is what I mean by "not appear to do anything" different.

**Comment by anubhavpulkit** [comment]
> No. That is what I mean by "not appear to do anything" different.

Unfortunately, there is no replacement for testing a cast other than testing on a Chromecast.

**Comment by cpg** [comment]
What?! What does that even mean in English?

If you mean to imply that I do not have a Chromecast-device, when I use the YT app, the icon is there and it works.

_As I already stated above._

If you do not mean that, please rephrase the sentence.

**Comment by anubhavpulkit** [comment]
> What?! What does that even mean in English?
> 
> If you mean to imply that I do not have a Chromecast-device, when I use the YT app, the icon is there and it works.
> 
> _As I already stated above._
> 
> If you do not mean that, please rephrase the sentence.

I mean 'Do you know any other method to test cast feature without Chromecast-device'. So I can't disturb you every time. 
Sorry, I think you get in the wrong way. My bad Sorry.

**Comment by cpg** [comment]
Casting through the media queue is working from #204

**Comment by chirag-jn** [comment]
For testing Google Cast, you can create a virtual Android TV device using Android Studio.

**Comment by anubhavpulkit** [comment]
> For testing Google Cast, you can create a virtual Android TV device using Android Studio.

we can test only Android app through this I think.

**Pull request closed without merging**
