### PR TITLE
Fix: forward of back multiple times is very annoying when the controls go away #129

### LINKED ISSUE #129: forward of back multiple times is very annoying when the controls go away
It looks like the timer that makes the controls go away when not used for a few seconds does not reset when the controls are touched.

the situation is very annoying when going back or forward multiple times in a row. typically the user will tap tap tap tap and after about 4 or so, the controls vanish. clearly a small bug in how that timer is handled.

### PR DESCRIPTION
**Pull request by codedentwickler**
Fix: Issue with Video player idle timer not resetting when controls are tapped repeatedly rapidly
closes #129

### CODE REVIEW

**Comment by cpg** [comment]
any thoughts on the above?

**Comment by codedentwickler** [comment]
Yes @cpg the issue was because when the video controls are touched repeatedly rapidly, the playtime does not change and the previous implementation depends on the playtime changing when play is reversed or fast forward. The playtime is stuck whenever it is pressed repeatedly. 

The fix I proposed in the PR is to reset the idle timer when the controls are touched even if playtime does not change.

**Comment by cpg** [comment]
That was not the question asked :-)

**Comment by codedentwickler** [comment]
My bad. Seems I don't understand the question then. Please can you explain

**Comment by cpg** [comment]
Basically, why are upgrades in VLCKit (or any other seeminly unrelated things) in this patch.

**Comment by codedentwickler** [comment]
Okay, I think the VLCKit version I have installed locally is old. I will upgrade and update this PR. Other changes in `Anywhere.xcodeproj/project.pbxproj` was generated by XCode.

**Comment by cpg** [comment]
BTW, we demoed Amahi to the authors of VideoLAN/VLCKit, Carola and JB (the head of the org).

**Comment by cpg** [comment]
I committed the relevant part to the `beta` branch. It does not seem to compile at the moment, so that branch is broken. Let's work on that, including upgrading the pods, in `beta`.

**Pull request closed without merging**
