### PR TITLE
Recreated Music Player

### PR DESCRIPTION
**Pull request by iswiftshek**
Designed the music player, used AVPlayer in place of AVQueuePlayer (to easily implement features like shuffle, play the previous item). #123 

image (11)

**Features added**
- Song, Artist, and Artwork on the screen
- Continuous music play 
- Skip to next/previous music file 
- Playlist functionality 
- On call interruption, music will resume playing when the call ends 
- Audio controls with artwork displayed on the lock screen 
- Music plays in the background thread
- Shuffle and Repeat functionality

**Improvements to be done**
- Cache the Artwork 
- Fix the jumpy time slider
- The slider on the lock screen/control screen changes the position of the file playing, but the changes in position from the music player won't reflect on the former
- The initial time to load and start the music player should be reduced 
- Manage audio session if the user plays audio on some other app 
- Handle the audio session with Bluetooth devices
- Improve the transition between the audio files (all info on the screen should be in better sync, like the way music player acts when playing downloaded audio files)

**Could be done**
- Close button be added in place of "Done"
- Show the current volume on the screen
- More metadata (Album name, Genre, etc.)

### CODE REVIEW

**Comment by cpg** [comment]
Not sure if you noticed, but there looks to be some white-space conflict in one file.

**Comment by cpg** [comment]
Build looking good. I will test for a few hours.

So far, the leftmost button does not seem to do anything. What is it supposed to do?

It also has an elongated horizontal size, making it look not so great. Maybe there is something amiss in the layout of it?

**Comment by iswiftshek** [comment]
By the leftmost button, I believe you mean the circular arrow button?
It is the repeat feature, for looping a particular song.

I fixed the layout. Looks better now:-

Screenshot 2019-06-14 at 12 28 57 am

**Comment by cpg** [comment]
I see. I had shuffle selected.

In other players, they are independent. There is no reason they should be linked.

Also the repeat has three "positions" -- none, repeat (all) and repeat-one.

**Comment by cpg** [comment]
How close can we get to that (the above)?

Also, I saw that play resumes after a call, but I have to test that some more.

**Comment by iswiftshek** [comment]
Right about the repeat feature, but by default we're playing all the files in the directory, so it doesn't make sense to have the repeat all option.

What we can do is disable the playlist functionality (looping of the files when the last one is reached), and have the repeat all feature.. if you like this idea better?

**Comment by cpg** [comment]
How about default that button to repeat all (which is what we do by default?) and the button then control the playlist behavior to follow the button from there on?

**Comment by iswiftshek** [comment]
To the best of what I've seen, the playlist behavior doesn't come default in the music players. For example, in Amazon Music, if we play a particular playlist.. all the songs play and then it stops when the playlist is over. 

Also if we default the repeat all feature, it would look a little off to have the repeat button already enabled when the user plays a music file.. so, how about we make the play all one-time default.. and let the user select if they want to repeat the already playing file or repeat all, or disable the repeat feature. 
How does that sound?

**Comment by cpg** [comment]
Sounds good

**Comment by iswiftshek** [comment]
Done!
I changed the repeat icon, not the best but we can change it anytime

Default
Screenshot 2019-06-14 at 12 30 42 pm

Reapeat all
Screenshot 2019-06-14 at 12 28 12 pm

Repeat current file
Screenshot 2019-06-14 at 12 29 58 pm

**Pull request merged**
