### PR TITLE
Redesigned Audio and Video Player

### PR DESCRIPTION
**Pull request by Marton-Zeisler**
Completely redesigned the audio player. I also added the following features:

- Swipe down to dismiss the player
- Swipe left to play next track
- Swipe right to play previous track

Simulator Screen Shot - iPhone 8 - 2019-07-13 at 00 19 16

I also added some layout optimisation to the video player and replaced the done button with a close button.

Simulator Screen Shot - iPhone 8 - 2019-07-13 at 00 49 06

### CODE REVIEW

**Comment by Marton-Zeisler** [comment]
@cpg, Could you tell me when exactly the swipe left/right gestures don't work properly? I tried it many times and it always works for me.

When you swipe left or right, you have to wait like a second for it to start playing as it loads the music

**Comment by cpg** [comment]
Yes, one has to wait, however, there is no feedback, so the user is left to find out what's happening. No progress indicators or the whole screen moving with the swipe or something.

Then the title changes first (and nothing else) and there is some wait, so it looks broken for a moment, the user wondering what's happening -- possibly swiping again or back ... it can be confusing.

**Comment by Marton-Zeisler** [comment]
@cpg Now it should be faster to load the music player.

Regarding the gestures, I agree that they feel a bit clunky, it's because I was just using a simple swipe gesture recognisers. 

Later I can do a proper swipe feature using collection views but that would be a lot of work so I will do that in a separate PR in the future.

**Comment by cpg** [comment]
Could you file an issue with the details of what happened with the gestures and explain what your thoughts are on what to do next?

**Pull request merged**
