### PR TITLE
files saved offline shows in Files app

### PR DESCRIPTION
**Pull request by iswiftshek**
I'm not sure if this is what was supposed to be done in #101 
It's already saving the files, but the plist wasn't updated to see them in the Files app.

Here's how it looks now:-
desk

### CODE REVIEW

**Comment by codedentwickler** [comment]
@iswiftshek When this feature was discussed, we intentionally implemented so that the user can access the offline files inside the app only. This lets us manage the state of files adequately as we have limited controls if the user can modifier the server files through the files app. 

Also, the user does not lose out on any advantage as we support sharing currently and the user can choose to do what they want with their files.

**Comment by iswiftshek** [comment]
@codedentwickler Yes, right, got it!
To the info.plist, I added "Supports opening documents in place" & "Application supports iTunes file sharing", and set them both to YES.

**Comment by codedentwickler** [comment]
Okay awesome. So what changes does this add. How much changes can the user make with the files app.

**Comment by iswiftshek** [comment]
Okay, so, what adding those two did was.. it wasn't initially showing the files that we stored offline in the Files app, now it does. 

The functionalities are the same as in the app: view, share, delete.

**Comment by codedentwickler** [comment]
Okay thanks for clarifying. I think you misunderstood me. The reason we didn’t add this earlier is because we don’t want the user to make changes to the files outside our app.

**Comment by codedentwickler** [comment]
I don’t think it’s necessary the user access the files in the Files App. Most apps data are not accessible in the Files App. 

If @cpg agrees this is necessary, we will need to update our current implementation to handle cases when the user modifies the files outside our app.

**Comment by iswiftshek** [comment]
> Okay thanks for clarifying. I think you misunderstood me. The reason we didn’t add this earlier is because we don’t want the user to make changes to the files outside our app.

Oh, okay. I thought that the Issue was to let the user make changes outside the app. Sorry :P

**Comment by codedentwickler** [comment]
No need to apologize, I think it's a good idea we discussed this. We might add this later if a user requests it or if @cpg thinks we should have it. We just need to update our current implementation to handle those cases.

**Comment by cpg** [comment]
1) I see some (unrelated?) commits (double-taps and gestures) in this PR. Was that in error?

2) As far as accessing files in the Files App. I honestly do not recall us discussing that (the issue of files modified outside our app) in depth.

The most I can find is the comment in the basic spec in #101, which hints that I thought it was a good idea for files to show in the Files app.

At this time, I don't really think modification of files would be a big problem and users probably do know that they did it, since it's their action that did it.

I would not object if we merged this, so long as it does not increase complexity significantly. That and making sure we do not mix other things that seem unrelated (see 1 above). Well, and resolve the conflicts.

**Pull request closed without merging**
