### PR TITLE
Added walkthrough screens

### PR DESCRIPTION
**Pull request by Marton-Zeisler**
I added the walkthrough screens to the app. I followed the design from the Android version.

User can swipe left and right to move between the walkthrough screens. After the user completed it, the app will show the login screen and mark the on-boarding completed in UserDefaults.

Simulator Screen Shot - iPhone 8 - 2019-05-23 at 22 47 59

Simulator Screen Shot - iPhone 8 - 2019-05-23 at 22 48 04

### CODE REVIEW

**Comment by cpg** [comment]
Upon testing this with my local `beta` branch (which is stlightly off the github `beta`, looks like), I do not see my HDA online. I could see it and browse it before with the prior app I had, so this shows a potential issue. Will have to research more.

**Comment by cpg** [comment]
Ok, I checked the origin `beta` branch and it appears to also be broken in the same respect.

So, there may well not be a problem with this PR, but we have to fix beta before merging this one.

**Comment by cpg** [comment]
The app in the app store (which I think it's `master`) is working.

**Comment by Marton-Zeisler** [comment]
Yeah, it must be an issue in the beta branch then because I did not touch any code related to the HDAs.

**Pull request closed without merging**
