### PR TITLE
Setting Area Implementation

### PR DESCRIPTION
**Pull request by baquer**
screen shot 2018-03-29 at 12 43 15 am

### CODE REVIEW

**Comment by cpg** [comment]
There are a lot of things that are not well with this PR
* the app crashed at least once while browsing
* the navigation header is lost upon returning to the app away from the settings area
* the icons are comically/ridiculously large
* the settings area settings don't work: Connection (three checkboxes that are independent), Feedback and Rate
* the signout is still in the main area

**Comment by codedentwickler** [comment]
@baquer You don't need to add an icon for back. Pushing the View Controller into the Navigation controller does that automatically. You can check how this was implemented in this flow Dashboard -> Shares -> Files. Notice the back button shows up automatically when push is used in place of present.

**Comment by baquer** [comment]
screen shot 2018-03-29 at 2 14 00 pm

**Comment by baquer** [comment]
@cpg all the bugs gets fixed , check it .

**Pull request closed without merging**
